import type { Pour } from "@/lib/pours";

/** Quiet sample journal so first open already feels like a lived-in notebook. */
export const SEED_POURS: Pour[] = [
  {
    id: "seed-heart",
    createdAt: "2026-09-11T09:20:00.000Z",
    photo: "/pours/heart.jpg",
    pattern: "heart",
    rating: 4,
    beans: "埃塞俄比亚 古吉",
    milk: "燕麦奶",
    grind: "中细",
    notes: "周末第一杯。奶泡够细，心形收口略偏右，下次提杯再干脆一点。",
    demo: true,
  },
  {
    id: "seed-tulip",
    createdAt: "2026-09-10T16:05:00.000Z",
    photo: "/pours/tulip.jpg",
    pattern: "tulip",
    rating: 5,
    beans: "危地马拉 安提瓜",
    milk: "全脂鲜奶",
    grind: "偏细",
    notes: "三层叠上去了。流速稳，叶片对称。今天的全脂特别听话。",
    demo: true,
  },
  {
    id: "seed-rosetta",
    createdAt: "2026-09-09T08:40:00.000Z",
    photo: "/pours/rosetta.jpg",
    pattern: "rosetta",
    rating: 3,
    beans: "哥伦比亚 慧兰",
    milk: "全脂鲜奶",
    grind: "中细",
    notes: "摆腕太快，叶子散了。杯里还剩空间，说明奶倒少了。",
    demo: true,
  },
  {
    id: "seed-swan",
    createdAt: "2026-09-08T14:12:00.000Z",
    photo: "/pours/swan.jpg",
    pattern: "swan",
    rating: 4,
    beans: "肯尼亚 涅里",
    milk: "全脂鲜奶",
    grind: "EK43 8",
    notes: "脖子拉出来了。翅膀还软，S 线可以再慢半拍。",
    demo: true,
  },
  {
    id: "seed-winged",
    createdAt: "2026-09-06T10:30:00.000Z",
    photo: "/pours/winged-heart.jpg",
    pattern: "winged-heart",
    rating: 4,
    beans: "埃塞俄比亚 耶加雪菲",
    milk: "燕麦奶",
    grind: "中细",
    notes: "左右翼第一次差不多齐。燕麦奶打发要更耐心，温度到 55°C 左右。",
    demo: true,
  },
  {
    id: "seed-phoenix",
    createdAt: "2026-09-04T18:50:00.000Z",
    photo: "/pours/phoenix.jpg",
    pattern: "phoenix",
    rating: 3,
    beans: "巴西 黄波旁",
    milk: "全脂鲜奶",
    grind: "意式",
    notes: "第一次试凤凰。扇羽还乱，先把中心身体站稳再扫尾。",
    demo: true,
  },
];
