/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as PourIdRouteImport } from './routes/pour.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPoursIdPhotoRouteImport } from './routes/api/pours.$id.photo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PourIdRoute = PourIdRouteImport.update({
  id: '/pour/$id',
  path: '/pour/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoursIdPhotoRoute = ApiPoursIdPhotoRouteImport.update({
  id: '/api/pours/$id/photo',
  path: '/api/pours/$id/photo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/pour/$id': typeof PourIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pours/$id/photo': typeof ApiPoursIdPhotoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/pour/$id': typeof PourIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pours/$id/photo': typeof ApiPoursIdPhotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/pour/$id': typeof PourIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pours/$id/photo': typeof ApiPoursIdPhotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/new'
    | '/pour/$id'
    | '/api/auth/$'
    | '/api/pours/$id/photo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/new'
    | '/pour/$id'
    | '/api/auth/$'
    | '/api/pours/$id/photo'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/new'
    | '/pour/$id'
    | '/api/auth/$'
    | '/api/pours/$id/photo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  PourIdRoute: typeof PourIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPoursIdPhotoRoute: typeof ApiPoursIdPhotoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pour/$id': {
      id: '/pour/$id'
      path: '/pour/$id'
      fullPath: '/pour/$id'
      preLoaderRoute: typeof PourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pours/$id/photo': {
      id: '/api/pours/$id/photo'
      path: '/api/pours/$id/photo'
      fullPath: '/api/pours/$id/photo'
      preLoaderRoute: typeof ApiPoursIdPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  PourIdRoute: PourIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPoursIdPhotoRoute: ApiPoursIdPhotoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
